function [fitresult, gof] = tanhfit(x, m)
%CREATEFIT(X,M)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: m
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Sep-2021 09:23:58


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, m );

% Set up fittype and options.
ft = fittype( 'c*tanh((x-a)/b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.Robust = 'Bisquare';
opts.StartPoint = [5e-10 -5e-08 1];
opts.TolFun = 1e-10;
opts.TolX = 1e-10;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'm vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'm', 'Interpreter', 'none' );
grid on


